"""
Export Macro Data from Parquet to CSV
=====================================
Reads the perfectly cleaned and aligned macro data generated by the 
Mini-Medallion pipeline (which already uses your FRED API key) and 
exports it to CSV for personal analysis.
"""

import pandas as pd
import os
import glob

RAW_DIR = r"E:\PRO\JIMxNik\jim_new\data\raw"
OUTPUT_DIR = r"E:\PRO\JIMxNik\jim_new\DataBase\macro_data"
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("=" * 60)
print("  MACRO DATA EXPORTER (From Pipeline Cache)")
print("=" * 60)

all_dfs = []

# Process all parquet files in the raw directory
for fp in glob.glob(os.path.join(RAW_DIR, "*.parquet")):
    filename = os.path.basename(fp)
    # We only care about FRED and Macro (Yahoo) files for this export
    if filename.startswith("fred_") or filename.startswith("macro_"):
        name = filename.replace(".parquet", "")
        try:
            df = pd.read_parquet(fp)
            
            # Make index timezone naive for safe concatenation later
            if isinstance(df.index, pd.DatetimeIndex) and df.index.tz is not None:
                df.index = df.index.tz_localize(None)
            
            # Export individual file
            out_path = os.path.join(OUTPUT_DIR, f"{name}.csv")
            df.to_csv(out_path)
            print(f"  [OK] Exported {name}.csv ({len(df)} rows)")
            
            # For the combined master file, rename columns to include the source prefix if needed
            # (FRED data already has unique columns like DFF, DFII10. Yahoo data usually has 'close')
            if name.startswith("macro_"):
                # Rename 'close' to the asset name (e.g., 'macro_dxy' -> 'dxy_close')
                asset_name = name.replace("macro_", "").upper()
                if "close" in df.columns:
                    df = df[['close']].rename(columns={'close': f"{asset_name}_close"})
                else:
                    df.columns = [f"{asset_name}_{c}" for c in df.columns]
            
            all_dfs.append(df)
        except Exception as e:
            print(f"  [ERROR] Failed to process {filename}: {e}")

# Create Master Combined File
if all_dfs:
    print("\n[INFO] Creating master combined file...")
    try:
        master_df = pd.concat(all_dfs, axis=1).sort_index().ffill()
        master_df.index.name = "date"
        master_path = os.path.join(OUTPUT_DIR, "macro_master_combined.csv")
        master_df.to_csv(master_path)
        print(f"  [OK] Master combined file: {len(master_df)} rows, {len(master_df.columns)} columns -> macro_master_combined.csv")
    except Exception as e:
        print(f"  [ERROR] Failed to create master combined file: {e}")

print(f"\n{'=' * 60}")
print(f"  All CSVs saved to: {OUTPUT_DIR}")
print(f"{'=' * 60}")
